spring.application.name=flightbook
spring.datasource.url=jdbc:mysql://localhost:3306/flightbook
spring.datasource.username=root
spring.datasource.password=Mani230252@#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tanishsingla03@gmail.com
spring.mail.password=xqjrypyqaqdgcwzo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.security.oauth2.client.registration.github.client-id=Ov23liRZx9RSIsyNC36r
spring.security.oauth2.client.registration.github.client-secret=39cfaa8420a36fddab4df7115714664f283b6b6c